const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const REPORTS_DIR = path.join(__dirname, '../reports');

const ensureReportsDir = function() {
    if (!fs.existsSync(REPORTS_DIR)) {
        fs.mkdirSync(REPORTS_DIR, { recursive: true });
    }
};

const generateExpensePDF = function(expenses, user, filters) {
    filters = filters || {};
    return new Promise(function(resolve, reject) {
        ensureReportsDir();

        const fileName = 'expense_report_' + user.id + '_' + Date.now() + '.pdf';
        const filePath = path.join(REPORTS_DIR, fileName);

        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const stream = fs.createWriteStream(filePath);

        doc.pipe(stream);

        // Header background
        doc.fillColor('#1e1b4b').rect(0, 0, 612, 100).fill();

        doc
            .fillColor('#ffffff')
            .fontSize(24)
            .font('Helvetica-Bold')
            .text('Expense Report', 50, 30);

        doc
            .fontSize(11)
            .font('Helvetica')
            .text('Generated for: ' + user.name, 50, 60)
            .text('Date: ' + new Date().toLocaleDateString(), 50, 76);

        doc.moveDown(2);

        // Filter info
        var summaryY = 120;
        if (filters.startDate || filters.endDate) {
            doc.fillColor('#6366f1').fontSize(12).font('Helvetica-Bold').text('Report Period:', 50, 120);
            doc.fillColor('#374151').fontSize(11).font('Helvetica')
                .text((filters.startDate || 'All time') + ' to ' + (filters.endDate || 'Present'), 50, 138);
            summaryY = 165;
        }

        // Summary
        var totalExpenses = expenses
            .filter(function(e) { return e.type === 'expense'; })
            .reduce(function(sum, e) { return sum + parseFloat(e.amount); }, 0);
        var totalIncome = expenses
            .filter(function(e) { return e.type === 'income'; })
            .reduce(function(sum, e) { return sum + parseFloat(e.amount); }, 0);
        var net = totalIncome - totalExpenses;
        var currency = user.currency || 'USD';

        doc.fillColor('#f3f4f6').roundedRect(50, summaryY, 512, 80, 8).fill();
        doc.fillColor('#ef4444').fontSize(12).font('Helvetica-Bold')
            .text('Total Expenses: ' + currency + ' ' + totalExpenses.toFixed(2), 70, summaryY + 14);
        doc.fillColor('#10b981')
            .text('Total Income: ' + currency + ' ' + totalIncome.toFixed(2), 70, summaryY + 34);
        doc.fillColor(net >= 0 ? '#6366f1' : '#ef4444')
            .text('Net Balance: ' + currency + ' ' + net.toFixed(2), 70, summaryY + 54);

        // Table header
        var tableY = summaryY + 100;
        doc.fillColor('#1e1b4b').rect(50, tableY, 512, 28).fill();
        doc.fillColor('#ffffff').fontSize(10).font('Helvetica-Bold')
            .text('Date', 58, tableY + 8)
            .text('Title', 120, tableY + 8)
            .text('Category', 280, tableY + 8)
            .text('Type', 370, tableY + 8)
            .text('Amount', 450, tableY + 8);

        // Table rows
        var rowY = tableY + 28;
        var rowIndex = 0;

        expenses.forEach(function(expense) {
            if (rowY > 720) {
                doc.addPage();
                rowY = 50;
            }

            var bgColor = rowIndex % 2 === 0 ? '#ffffff' : '#f9fafb';
            doc.fillColor(bgColor).rect(50, rowY, 512, 24).fill();

            var catName = (expense.category && expense.category.name) ? expense.category.name : 'N/A';

            doc.fillColor('#374151').fontSize(9).font('Helvetica')
                .text(expense.date, 58, rowY + 7)
                .text(expense.title.substring(0, 22), 120, rowY + 7)
                .text(catName.substring(0, 15), 280, rowY + 7)
                .fillColor(expense.type === 'expense' ? '#ef4444' : '#10b981')
                .text(expense.type, 370, rowY + 7)
                .text(parseFloat(expense.amount).toFixed(2), 450, rowY + 7);

            rowY += 24;
            rowIndex++;
        });

        // Footer
        doc.fillColor('#9ca3af').fontSize(8).font('Helvetica')
            .text('Generated by Expense Tracker App', 50, doc.page.height - 40, { align: 'center' });

        doc.end();

        stream.on('finish', function() { resolve({ fileName: fileName, filePath: filePath }); });
        stream.on('error', reject);
    });
};

module.exports = { generateExpensePDF };